/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package editordetexto;


import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Desktop;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.LineNumberReader;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Ronald_PC_2
 */
public class TelaPrincipal extends javax.swing.JFrame {
    String diretorioSalvar="";
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        this.setTitle("BIZUDIT");
        jTextArea.setLineWrap(true);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuNovo = new javax.swing.JMenuItem();
        jMenuAbrir = new javax.swing.JMenuItem();
        jMenuSalvar = new javax.swing.JMenuItem();
        jMenupdf = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuVerificarRepeticoes = new javax.swing.JMenuItem();
        TirarPontuacoes = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuAjudSobre = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        jMenu4.setText("jMenu4");

        jMenuItem5.setText("jMenuItem5");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(467, 354));

        jTextArea.setColumns(20);
        jTextArea.setRows(5);
        jTextArea.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextArea.setMinimumSize(new java.awt.Dimension(0, 0));
        jScrollPane1.setViewportView(jTextArea);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jMenu1.setText("arquivos");

        jMenuNovo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuNovo.setText("Novo");
        jMenuNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuNovoActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuNovo);

        jMenuAbrir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_MASK));
        jMenuAbrir.setText("Abrir");
        jMenuAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAbrirActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuAbrir);

        jMenuSalvar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuSalvar.setText("Salvar");
        jMenuSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSalvarActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuSalvar);

        jMenupdf.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        jMenupdf.setText("Salvar Pdf Desktop");
        jMenupdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenupdfActionPerformed(evt);
            }
        });
        jMenu1.add(jMenupdf);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Funções");

        jMenuVerificarRepeticoes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        jMenuVerificarRepeticoes.setText("Verificar Repetições das Palavras");
        jMenuVerificarRepeticoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuVerificarRepeticoesActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuVerificarRepeticoes);

        TirarPontuacoes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_MASK));
        TirarPontuacoes.setText("Tirar pontuações e preposições");
        TirarPontuacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TirarPontuacoesActionPerformed(evt);
            }
        });
        jMenu2.add(TirarPontuacoes);

        jMenuBar1.add(jMenu2);

        jMenu5.setText("Ajuda");

        jMenuAjudSobre.setText("Sobre");
        jMenuAjudSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAjudSobreActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuAjudSobre);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuNovoActionPerformed
        diretorioSalvar="";
        jTextArea.setText("");
    }//GEN-LAST:event_jMenuNovoActionPerformed

    private void jMenuAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAbrirActionPerformed
       JFileChooser fc=new JFileChooser();
        fc.showOpenDialog(this);
        fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
       File f= fc.getSelectedFile();
        //jTextArea.setText(f.getPath());
        FileReader fr = null;
        try {
            fr = new FileReader(f.getPath());
            diretorioSalvar=f.getPath();
            System.out.println(diretorioSalvar);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        LineNumberReader lnr = new LineNumberReader(fr);
        String s, a = "";
        try {
            while ((s = lnr.readLine()) != null) {
                a = a + s+"\n";
            }
            jTextArea.setText(a);
        } catch (IOException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            lnr.close();
        } catch (IOException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            fr.close();
        } catch (IOException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuAbrirActionPerformed

    private void jMenuSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSalvarActionPerformed
       if(diretorioSalvar.equals("")){
           JFileChooser fc=new JFileChooser();
        fc.showOpenDialog(this);
        fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
       File f= fc.getSelectedFile();
      //jTextArea.setText(f.getPath());
       
       File arq = new File(f.getPath()+".bizu");//daqui pra baixo é a parte que adiciona no arquivo .txt
        FileWriter fw = null;
           try {
               fw = new FileWriter(arq);
           } catch (IOException ex) {
               Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
           }
           try {
               //System.out.println(map.toString());
               fw.write(jTextArea.getText());
           } catch (IOException ex) {
               Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
           }
           try {
               fw.close();
           } catch (IOException ex) {
               Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
           }
       
       
       }else{
           File arq = new File(diretorioSalvar);//daqui pra baixo é a parte que adiciona no arquivo .txt
        FileWriter fw = null;
           try {
               fw = new FileWriter(arq);
           } catch (IOException ex) {
               Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
           }
        System.out.println(jTextArea.getText());
           try {
               fw.write(jTextArea.getText());
           } catch (IOException ex) {
               Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
           }
           try {
               fw.close();
           } catch (IOException ex) {
               Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
           }
       }
    }//GEN-LAST:event_jMenuSalvarActionPerformed

    private void jMenuAjudSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAjudSobreActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "DESENVOLVIDO COMO REQUISITO DE NOTA NA\nDISCIPLINA DE SISTEMAS MULTIMÍDIA NA FACULDADE DE  \nENGENHARIA DE COMPUTAÇÃO");
    }//GEN-LAST:event_jMenuAjudSobreActionPerformed

    private void jMenuVerificarRepeticoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuVerificarRepeticoesActionPerformed

        Funcoes procPalav = new Funcoes();

        
        JOptionPane.showMessageDialog(this, "15 PALAVRAS MAIS REPETIDAS\n\n"+procPalav.repeticoesPalavras(jTextArea.getText()));
        
       
       
    }//GEN-LAST:event_jMenuVerificarRepeticoesActionPerformed

    private void TirarPontuacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TirarPontuacoesActionPerformed
        Funcoes procPalav = new Funcoes();

        jTextArea.setText(procPalav.tirarPontuacao(jTextArea.getText()));


    }//GEN-LAST:event_TirarPontuacoesActionPerformed

    private void jMenupdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenupdfActionPerformed
                                                 
        // exportar como pdf
         Document document = new Document();
        JFileChooser fc=new JFileChooser();
        fc.showOpenDialog(this);
        fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
       File f= fc.getSelectedFile();
        try {
            PdfWriter.getInstance(document, new FileOutputStream(f.getPath()+".pdf"));
            
            document.open();
            document.add(new Paragraph(jTextArea.getText()));
            
        } catch (DocumentException | FileNotFoundException ex) {
            System.out.println("Error:"+ex);
        }finally{
            document.close();
        }
        
        try {
            Desktop.getDesktop().open(new File(f.getPath()+".pdf"));
        } catch (IOException ex) {
            System.out.println("Error:"+ex);
        }
        
    }//GEN-LAST:event_jMenupdfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem TirarPontuacoes;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuItem jMenuAbrir;
    private javax.swing.JMenuItem jMenuAjudSobre;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuNovo;
    private javax.swing.JMenuItem jMenuSalvar;
    private javax.swing.JMenuItem jMenuVerificarRepeticoes;
    private javax.swing.JMenuItem jMenupdf;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea;
    // End of variables declaration//GEN-END:variables
}
